#!/usr/bin/python3
""" sys module """

save_to_json_file = __import__('5-save_to_json_file').save_to_json_file
load_from_json_file = __import__('6-load_from_json_file').load_from_json_file
import sys

sys.argv[1] = []
save_to_json_file(sys.argv[1][1:], "add_item.json")
data = load_from_json_file("add_item.json")
print(data)
